# Site config
locale: "en-US"
title: Code with Brian Short
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and happenings in my corner of the world
baseurl: ""
url: "https://www.codeshort.io"
paginate: 5

# Author profile
author:
  name: "Brian Short"
  avatar: "assets/images/me.jpg"
  bio: "I'm a software developer who likes to write maintainable code.
  I love good documentation."
  email: brian@codeshort.io
  uri: "https://www.codeshort.io"
  github: brianshortnh
  linkedin: brianshortnh

# Theme skin
minimal_mistakes_skin: "dark"

# Includes
include: ["_pages"]

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
