# Site config
title: Code with Brian Short
email: brian@codeshort.io
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and happenings in my corner of the world
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codeshort.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: brianshortnh

# Theme skin
minimal_mistakes_skin: "dark"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
